name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
  clippy:
    needs: build
    runs-on: windows-2019
    steps:
      - run: cargo clippy
  tests:
    needs: build
    runs-on: windows-2019
    steps:
      - run: cargo test --verbose
  formatting:
    needs: build
    runs-on: windows-2019
    steps:
      - run: cargo fmt -- --check